### ISSUE TITLE
German FAQs are mixed with english texts

### ISSUE THREAD

**Issue by Sonstwer** [Netzfreiheit/STI-UI#131]
https://savetheinternet.eu/de/faq/

do we have the translations somewhere so that i can update this page?

**Comment by musha68k** [comment]
Hi @Sonstwer seems like only the headlines have been translated so far /cc @socialhack @sebalis

**Comment by sebalis** [comment]
This is true. I’m sorry for getting round to it earlier. Today’s German Big Brother Awards gala took over my time. (I translated a lot into English and will interpret into English live tonight, audio available on the stream page.)

**Comment by socialhack** [comment]
@sebalis do you think you'll be able to translate the FAQs in the next week or should we ping a few more volunteers?

**Comment by sebalis** [comment]
I want to do it, will try to deliver something by mid-week.

**Comment by sebalis** [comment]
I must say I’m not very happy with the “Specialised Services” in the FAQs. 1. Traditionally FAQs should be a collection of individual questions and the answers should as much as possible be understandable if read in isolation. It seems to me that a longer text has simply been structured by question headlines. And the questions have not been chosen well: 2. The question whose headline is “What are examples of services that are not specialised services?” completely fails to deliver on its promise, as the answer contains no single example, only a definition. 3. The two questions on safeguards regarding specialised services are potentially misleading (not the answers). The initial message might that specialised services need to be protected in some way. But of course the real issue is to tighten the definition of what is a specialised service, to avoid the term to be applied too widely. This should be reflected in the questions.

Can this be improved or is it too late because we have too many translations already?

**Comment by sebalis** [comment]
Also, I think there is a plain error in the summary of the “five safeguards for the provision of specialised services”, item 2. The summary says that specialised services have to be optimised to assure specific quality of the content, application or service. But I don’t see this as the core of this particular safeguard. The regulation does say in (16) that being optimised for specific content, applications or services is part of the definition of a specialised service. But the actual safeguard is that the “optimisation” must be necessary to meet the requirements of the content, applications, or services. This is not reflected in our FAQ answer at all. Also I wondered what the meaning of “optimisation” might be. If it is simply traffic optimisation, then the statement “specialised services have to be optimised to assure specific quality of service requirements of the content, application or service” is not very meaningful in my view.

**Comment by sebalis** [comment]
I’ve received some clarification and will now continue somehow.

**Comment by sebalis** [comment]
Pull request #152 now (finally) created, containing a full German translation of the FAQ. Please review and merge.

**Comment by PublicScam** [comment]
@socialhack gave me the ok to merge this in 0151eccbab75ef575dff282d92bd4f818494fb77. Thanks @sebalis for taking the time to translate!
