### ISSUE TITLE
"go to submission" button besides "more" and "back"

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#46]
We want a Button on Step 1 and 2 which brings the user directly to step 4. 
People can finish the questionnaire on all steps as all fields are optional as long as one input has been given (this is already implemented).

**Comment by yaoyuanpa** [comment]
I suggest adding that button in step 1 and 2 as soon as the user has made an input. In step 3 we could replace the Next button for the Go to submission button, so it is clear that Go to submission means going to step 4. 

I think we somehow have to let the user know what is mandatory for him and what is not. We could add a little note in the explanation text above the iframe.

Also, this would mean that we could delete the word "optional" from step 2 and 3 in the step navigation, because all steps are now optional, as long as anything has been entered – right? 

![screen shot 2016-03-22 at 13 03 26](https://cloud.githubusercontent.com/assets/17917499/13951014/9aa935f8-f02e-11e5-8878-6ea77250b96d.png)
