### ISSUE TITLE
show user response text for multiple choice options

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#63]
The user needs to see the text for multiple choice options so that he/she can make an informed decision. I'd suggest a similar UI as the explanation text. 
https://trello.com/c/z16CSa5u/52-show-user-response-text-for-multiple-choice-options

**Comment by yaoyuanpa** [comment]
Yes, I'd suggest that too. It ultimately depends on whether you want the user to know that this text will end up in his message, because the same UI element in step 2 is "only" for explanation. We could still do it and change the explanatory texts in step 1 and step 2 to avoid confusion @socialhack 

If you could style the dropdown arrow and the message texts the same way as in step 2 and 3, that would be great! @ondrejpialek @filipesousa20 

![screen shot 2016-03-23 at 09 47 51](https://cloud.githubusercontent.com/assets/17917499/13980475/1e34b554-f0df-11e5-83e5-70bd3b18ce9e.png)
