### ISSUE TITLE
too much white color on header image

### ISSUE THREAD

**Issue by socialhack** [Netzfreiheit/STI-UI#73]
an experienced campaign person commented that we have a lot of "empty space" in the header image. Could we maybe use stronger colours on this image instead of the white? 
http://grab.by/P0Ve
http://grab.by/P0Wi

This is a question of style and not a clear demand. But if others share this concern then we could maybe think about slight modifications of the header image.

**Comment by maltefiala** [comment]
This relates to #41 , will close old issue and let's continue here.

**Comment by maltefiala** [comment]
We prepared a different version. If it's ok for you, let's use this one:
![header-sujet-draft13](https://cloud.githubusercontent.com/assets/526184/14023099/166961bc-f1e3-11e5-9325-ca11637b4b4e.png)

**Comment by yaoyuanpa** [comment]
I absolutely agree. When you look at the placeholder image in the mockup, you see that the black in the foreground really pops off the screen and gives it a stronger feel @maltefiala Can we ask Clarissa to make some changes once more? I really think that introducing black to the foreground (i.e. the closest hands) would make a huge difference. Right now there's nowhere for the eye to focus on, kind of like a wallpaper. (Plus, I really prefer the first draft with the megaphone, because the shape of the cable isn't strong enough to make a focal point)
![screen shot 2016-03-24 at 19 23 22](https://cloud.githubusercontent.com/assets/17917499/14027148/8272aba8-f1f6-11e5-8954-9852a15bf9b6.png)

**Comment by maltefiala** [comment]
On it's way

**Comment by maltefiala** [comment]
![header-sujet-draft14](https://cloud.githubusercontent.com/assets/526184/14041834/f2cc59ca-f274-11e5-880e-dac51bb93efa.png)
![header-sujet-draft15](https://cloud.githubusercontent.com/assets/526184/14041835/f2d49dba-f274-11e5-8b73-241c4e6456e4.png)
